global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:80']

  - job_name: 'order-tracking-service'
    static_configs:
      - targets: ['order-tracking-service:5000']

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:4003']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:4004']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 